### ISSUE TITLE
Add "Convince Your Boss" page

### ISSUE THREAD

**Issue by emstanley** [emstanley/refactr_web_app#18]
- [ ] Add a button to the homepage under the pricing tables

**Comment by ambanks** [comment]
Trying to convince your boss to buy you a ticket to REFACTR.TECH? Let us help! We have a couple of tips for you: 

1. Check with your manager to see if there is a 2019 training budget you can use, or if there are funds that will become available in 2020. 

2. With the new year coming up, this is a good time to discuss a potential raise or bonus. If your company doesn't offer a training budget, this is a good time to negotiate an annual company-paid training allowance.

3. Let your manager know that you will share what you learn at REFACTR.TECH with the rest of the team. You could also offer to give a talk to the company and share your experience or a technical topic you learned about.

You can use the following letter as a blueprint and customize to include details about which sessions you plan to attend and which [speakers](http://www.refactr.tech/speakers) you plan to meet! 

**_Sample Letter:_**

Hello [boss’s name here],

I’m reaching out to request your help to attend an amazing conference, [REFACTR.TECH](https://refactr.tech/) in Atlanta, GA on April 23 - 24, 2020 [April 22 - 24, 2020 if you want to include a workshop]. The 2nd annual [REFACTR.TECH](http://www.refactr.tech/) is a tech conference that focuses on creating an inclusive environment, featuring marginalized people, and allies doing amazing work.

The conference provides content valuable to a wide range of experience levels and interests. Technical topics of interest from intermediate to senior developers, alongside beginner-friendly sessions and workshops, are all part of the event. It includes a combination of 3 [workshops](http://www.refactr.tech/workshops), 4 keynote sessions, and 50 track [sessions](http://www.refactr.tech/speakers) to expand knowledge, hone technical skills, and make important connections.

At [REFACTR.TECH](http://www.refactr.tech/) I will have the opportunity to highlight [your company name] while meeting amazing people. When I return, I’ll be able to contribute to our expanding knowledge and skills as well as make a significant contribution to our company culture and the broader tech community.
The cost of my attendance would be:

Conference: $275 
OR
Conference plus workshop: $400 

Thank you for your consideration! I look forward to counting our company amongst forward-thinking, supportive and encouraging places to work.

Looking forward to hearing from you,
[Your Name]
