### ISSUE TITLE
Dynamically crop speaker images with square aspect ratio

### ISSUE THREAD

**Issue by emstanley** [emstanley/refactr_web_app#22]
css cropped to 1:1 square aspect ratio, preferred min size 500px

**Comment by ambanks** [comment]
@emstanley there is a new photo in Airtable for Angeleen so you might not need to fix her image.

**Comment by emstanley** [comment]
@ambanks it was a square image so it didn't need fixing.

<img width="256" alt="Screenshot 2019-11-26 01 02 50" src="https://user-images.githubusercontent.com/664894/69603441-ae572f00-0fe8-11ea-81a4-0fdd17739b51.png">
