### ISSUE TITLE
Fix organizer photos on the About page

### ISSUE THREAD

**Issue by emstanley** [emstanley/refactr_web_app#36]
- [x] standardize image size for organizer photos

New title, who dis?
- [x] Update title for Angel to: "Technical Expert, Thinkful"
- [x] Update title for Erica to "Sr. Engineering Manager, Mozilla"

**Comment by ambanks** [comment]
Update title for Angel to: "Technical Expert, Thinkful" 
Update title for Erica to "Sr. Engineering Manager, Mozilla"
